"""Configuration for Freddie Mac annual sample processing."""

ORIGINATION_COLUMNS = [
    "CLASSIC FICO",
    "FIRST PAYMENT DATE",
    "FIRST TIME HOMEBUYER INDICATOR",
    "MATURITY DATE",
    "METROPOLITAN STATISTICAL AREA (MSA) OR METROPOLITAN DIVISION",
    "MORTGAGE INSURANCE PERCENTAGE (MI %)",
    "NUMBER OF UNITS",
    "OCCUPANCY STATUS",
    "ORIGINAL COMBINED LOAN-TO-VALUE (CLTV)",
    "ORIGINAL DEBT-TO-INCOME (DTI) RATIO",
    "ORIGINAL UPB",
    "ORIGINAL LOAN-TO-VALUE (LTV)",
    "ORIGINAL INTEREST RATE",
    "CHANNEL",
    "PREPAYMENT PENALTY INDICATOR",
    "AMORTIZATION TYPE",
    "PROPERTY STATE",
    "PROPERTY TYPE",
    "POSTAL CODE",
    "LOAN IDENTIFIER",
    "LOAN PURPOSE",
    "ORIGINAL LOAN TERM",
    "NUMBER OF BORROWERS",
    "SELLER NAME",
    "SUPER CONFORMING FLAG",
    "PRE-HARP LOAN SEQUENCE NUMBER",
    "SPECIAL ELIGIBILITY PROGRAM",
    "HARP INDICATOR",
    "PROPERTY VALUATION METHOD",
    "INTEREST ONLY (I/O) INDICATOR",
    "VANTAGESCORE 4.0",
]


ORIGINATION_STRING_COLUMNS = {
    "FIRST TIME HOMEBUYER INDICATOR": "string",
    "OCCUPANCY STATUS": "string",
    "CHANNEL": "string",
    "PREPAYMENT PENALTY INDICATOR": "string",
    "AMORTIZATION TYPE": "string",
    "PROPERTY STATE": "string",
    "PROPERTY TYPE": "string",
    "POSTAL CODE": "string",
    "LOAN IDENTIFIER": "string",
    "LOAN PURPOSE": "string",
    "SELLER NAME": "string",
    "SUPER CONFORMING FLAG": "string",
    "PRE-HARP LOAN SEQUENCE NUMBER": "string",
    "SPECIAL ELIGIBILITY PROGRAM": "string",
    "HARP INDICATOR": "string",
    "INTEREST ONLY (I/O) INDICATOR": "string",
}


NUMERIC_SENTINELS = {
    "ORIGINAL DEBT-TO-INCOME (DTI) RATIO": 999,
    "ORIGINAL LOAN-TO-VALUE (LTV)": 999,
    "ORIGINAL COMBINED LOAN-TO-VALUE (CLTV)": 999,
    "PROPERTY VALUATION METHOD": 7,
}


CATEGORICAL_SENTINELS = {
    "FIRST TIME HOMEBUYER INDICATOR": "9",
}


POSTAL_CODE_WIDTH = 3